# Generated by Django 3.2 on 2021-05-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='price',
        ),
    ]
